version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/db1?useUnicode=true&characterEncoding=utf8&useSSL=false
    networks:
      - backend
    ports:
      - "3333:3333"
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: eric
      MYSQL_PASSWORD: eric
      MYSQL_DATABASE: db1
    volumes:
      - db-data:/var/lib/mysql/
    ports:
    - 3306:3306
    networks:
      - backend


networks:
  backend:
    driver: bridge

volumes:
  db-data: